#!/usr/bin/env python3
"""FORK-ONLY: add the one Linux-only artifact the upstream lock is missing.

`gradle/verification-metadata.xml` was generated on a Windows machine
(0 occurrences of "-linux" in the whole file) and pins only
`aapt2-9.1.1-14792394-windows.jar`. On Linux, AGP resolves
`com.android.tools.build:aapt2:9.1.1-14792394:aapt2-9.1.1-14792394-linux.jar`
through an internal detached configuration, and strict dependency
verification fails the build:

    > Dependency verification failed for configuration ':app:detachedConfiguration2'
      One artifact failed verification: aapt2-9.1.1-14792394-linux.jar

Rather than weakening verification for the entire build
(`--dependency-verification=off|lenient`) or blindly accepting whatever the
resolver returns (`--write-verification-metadata`), this script adds exactly
that one entry with a checksum fetched out-of-band from Google Maven:

    https://dl.google.com/dl/android/maven2/com/android/tools/build/aapt2/9.1.1-14792394/aapt2-9.1.1-14792394-linux.jar
    sha256 e7ae17af6e4093c771243e82d66462353de87befaac206bfb43e557ac1c34440  (2,331,128 bytes)

Everything else stays strict: existing pins are untouched, and any further
unpinned artifact still fails the build loudly. Upstream is not modified.
"""
import sys
from pathlib import Path

GROUP = "com.android.tools.build"
COMPONENT = "aapt2"
VERSION = "9.1.1-14792394"
ARTIFACT = f"{COMPONENT}-{VERSION}-linux.jar"
SHA256 = "e7ae17af6e4093c771243e82d66462353de87befaac206bfb43e557ac1c34440"

OPEN_TAG = f'<component group="{GROUP}" name="{COMPONENT}" version="{VERSION}">'


def main():
    path = Path(sys.argv[1] if len(sys.argv) > 1 else "gradle/verification-metadata.xml")
    text = path.read_text(encoding="utf-8")
    if f'name="{ARTIFACT}"' in text:
        print(f"OK already listed: {ARTIFACT}")
        return
    start = text.index(OPEN_TAG)
    end = text.index("</component>", start)
    newline = "\r\n" if "\r\n" in text else "\n"
    # Keep the whitespace that separates the last artifact from </component>
    # so the inserted block lines up with its siblings.
    head = text[:end]
    body = head.rstrip()
    gap = head[len(body):]
    block = newline.join([
        f'         <artifact name="{ARTIFACT}">',
        f'            <sha256 value="{SHA256}" origin="Generated by Gradle"/>',
        '         </artifact>',
    ])
    path.write_text(body + newline + block + gap + text[end:], encoding="utf-8")
    print(f"OK added {ARTIFACT} sha256={SHA256[:16]}... to {path}")


if __name__ == "__main__":
    main()
